name: Develop CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build_server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./server
      run: dotnet restore
    - name: Build
      working-directory: ./server
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./server
      run: dotnet test --no-build --verbosity normal
  build_client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      working-directory: ./client
      run: npm ci
    - name: Build     
      working-directory: ./client
      run: npm run build
