name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build_server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./server
      run: dotnet restore
    - name: Build
      working-directory: ./server
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./server
      run: dotnet test --no-build --verbosity normal
